name: private_library
description: "Biblioteca pessoal."
publish_to: 'none' 

version: 1.0.0+3

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  auto_size_text: 
  loading_animation_widget: ^1.2.0+4
  mask_text_input_formatter: ^2.8.0 
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.4
  intl_translation:
  provider:
  sqflite: 
  path_provider: 
  flutter_barcode_scanner: ^2.0.0
  awesome_icons:
  url_launcher:
  flutter_native_splash: 
  flutter_launcher_icons: 
  flutter_app_name: 
  shared_preferences: 
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1


flutter:

  uses-material-design: true
  assets:
   - assets/images/icons/
   - assets/images/logo/
   - assets/images/


flutter_native_splash:
  color: "#6D95A9"
  image: assets/images/icon.png
  android: true

flutter_icons:
  image_path: "assets/images/icon.png"
  android: true
  ios: true

flutter_app_name: 
  name: "Minha Biblioteca"
